#!/bin/sh

JSONPATH="$(jq -r .gamepath "$XDG_CONFIG_HOME/viper.json" 2> /dev/null)"
GAMEPATH="${GAMEPATH:-$JSONPATH}"

LATESTJSON=""

[ "$GAMEPATH" = "" ] && {
	echo "err: \$GAMEPATH not set, and or viper.json was not able to be read."
	exit 1
}

[ ! -d "$GAMEPATH" ] && {
	echo "err: '$GAMEPATH' does not exist!"
	exit 1
}

exclude() {
	EXCLUDE="
		ns_startup_args.txt
		ns_startup_args_dedi.txt
	"

	[ "$1" = "--revert" ] && {
		for i in $EXCLUDE; do
			mv "$GAMEPATH"/"$i.excluded" "$GAMEPATH"/"$i"
		done

		return
	}

	for i in $EXCLUDE; do
		mv "$GAMEPATH"/"$i" "$GAMEPATH"/"$i.excluded"
	done
}

latest() {
	[ "$LATESTJSON" = "" ] && {
		LATESTJSON="$(curl --silent 'https://api.github.com/repos/R2Northstar/Northstar/releases/latest')"
	}

	case $1 in
		"ver") /bin/echo "$LATESTJSON" | jq -r .tag_name;;
		"zip") /bin/echo "$LATESTJSON" | jq -r .assets[0].browser_download_url;;
	esac
}

for i in $@; do
	case $i in
		"--update")
			cd "$GAMEPATH"

			[ "$(cat ns_version.txt 2> /dev/null)" = "$(latest ver)" ] && {
				echo "$@" | grep -qe "--force" || {
					echo "Already on newest version!"
					exit 0
				}
			}
			
			ZIP="$(latest zip)"
			LOCALZIP="$(echo $ZIP | sed 's/.*\///g')"

			echo "Downloading zip..."
			wget "$ZIP" > /dev/null

			exclude

			echo "Extracting zip..."
			unzip -oqq "$LOCALZIP"
			rm "$LOCALZIP"

			exclude --revert

			latest ver > ns_version.txt
			echo "Finished updating to: $(latest ver)"
			;;
		"--force") ;;
		*)	echo "err: Unknown argument, '$i'";;
	esac
done
